package oriolvillaret.com.speedrun.models.mappers;

import com.google.gson.Gson;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import oriolvillaret.com.api_connection_lib.models.Run;
import oriolvillaret.com.speedrun.models.Record;

import static org.junit.Assert.assertEquals;

public class RecordMapperTest {

    static String record1 = "{\"weblink\":\"https://www.speedrun.com/.hack_g.u._volume_1_rebirth#Any\",\"game\":\"pd0y226e\",\"category\":\"jdrqw4gk\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/pd0y226e\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/jdrqw4gk\"}]}";
    static String record2 = "{\"weblink\":\"https://www.speedrun.com/.hack_g.u._volume_1_rebirth#Any_NG%2B\",\"game\":\"pd0y226e\",\"category\":\"jdz3rz32\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"zn88433z\",\"weblink\":\"https://www.speedrun.com/.hack_g.u._volume_1_rebirth/run/zn88433z\",\"game\":\"pd0y226e\",\"level\":null,\"category\":\"jdz3rz32\",\"videos\":{\"links\":[{\"uri\":\"https://www.twitch.tv/videos/137315010\"}]},\"comment\":\"I think it can go lower.\\r\\n\\r\\nI think it can go sub 2:50\",\"status\":{\"status\":\"verified\",\"examiner\":\"qjoee786\",\"verify-date\":\"2017-04-22T13:56:28Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"qjoee786\",\"uri\":\"https://www.speedrun.com/api/v1/users/qjoee786\"}],\"date\":\"2017-04-22\",\"submitted\":\"2017-04-22T13:56:28Z\",\"times\":{\"primary\":\"PT2H55M58S\",\"primary_t\":10558,\"realtime\":\"PT2H55M58S\",\"realtime_t\":10558,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"n5e17e27\",\"emulated\":true,\"region\":\"pr184lqn\"},\"splits\":null,\"values\":{}}},{\"place\":2,\"run\":{\"id\":\"zg7wwqjz\",\"weblink\":\"https://www.speedrun.com/.hack_g.u._volume_1_rebirth/run/zg7wwqjz\",\"game\":\"pd0y226e\",\"level\":null,\"category\":\"jdz3rz32\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=glXiMu6oSf4\"}]},\"comment\":\"first run, still have a lot to learn, but nice time to start with for now\",\"status\":{\"status\":\"verified\",\"examiner\":\"48ge6kyj\",\"verify-date\":\"2018-08-24T23:24:20Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"48gym78p\",\"uri\":\"https://www.speedrun.com/api/v1/users/48gym78p\"}],\"date\":\"2018-07-24\",\"submitted\":\"2018-07-24T20:36:04Z\",\"times\":{\"primary\":\"PT3H49M32S\",\"primary_t\":13772,\"realtime\":\"PT3H49M32S\",\"realtime_t\":13772,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"n5e17e27\",\"emulated\":false,\"region\":\"pr184lqn\"},\"splits\":null,\"values\":{}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/pd0y226e\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/jdz3rz32\"}]}";
    static String record3 = "{\"weblink\":\"https://www.speedrun.com/meow#Any_Good_Ending\",\"game\":\"46wxo91r\",\"category\":\"w20zx3vd\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"9yo0ll1y\",\"weblink\":\"https://www.speedrun.com/meow/run/9yo0ll1y\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"w20zx3vd\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=kqWZ_1erYlo\"}]},\"comment\":\"Not too bad but room for improvement.\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2016-08-23T02:44:27Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"zxz9kn8q\",\"uri\":\"https://www.speedrun.com/api/v1/users/zxz9kn8q\"}],\"date\":\"2016-08-23\",\"submitted\":\"2016-08-23T02:44:27Z\",\"times\":{\"primary\":\"PT4M5S\",\"primary_t\":245,\"realtime\":\"PT4M5S\",\"realtime_t\":245,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}},{\"place\":2,\"run\":{\"id\":\"m7pd51em\",\"weblink\":\"https://www.speedrun.com/meow/run/m7pd51em\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"w20zx3vd\",\"videos\":{\"links\":[{\"uri\":\"https://www.twitch.tv/videos/306368512\"}]},\"comment\":\"hehe funni cat goes meow\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2018-09-06T12:07:45Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"18qkywq8\",\"uri\":\"https://www.speedrun.com/api/v1/users/18qkywq8\"}],\"date\":\"2018-09-05\",\"submitted\":\"2018-09-05T22:00:57Z\",\"times\":{\"primary\":\"PT4M13S\",\"primary_t\":253,\"realtime\":\"PT4M13S\",\"realtime_t\":253,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/46wxo91r\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/w20zx3vd\"}]}";
    static String record4 = "{\"weblink\":\"https://www.speedrun.com/meow#Any_Bad_Ending\",\"game\":\"46wxo91r\",\"category\":\"wdmqv6x2\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"9mewk68m\",\"weblink\":\"https://www.speedrun.com/meow/run/9mewk68m\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"wdmqv6x2\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=UYYxEiQ-GTg\"}]},\"comment\":\"Frame perfect run!\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2016-08-09T03:12:18Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"zxz9kn8q\",\"uri\":\"https://www.speedrun.com/api/v1/users/zxz9kn8q\"}],\"date\":\"2016-08-09\",\"submitted\":\"2016-08-09T03:12:18Z\",\"times\":{\"primary\":\"PT33S\",\"primary_t\":33,\"realtime\":\"PT33S\",\"realtime_t\":33,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}},{\"place\":1,\"run\":{\"id\":\"z036308z\",\"weblink\":\"https://www.speedrun.com/meow/run/z036308z\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"wdmqv6x2\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=89MfBydlqY8\"}]},\"comment\":\"Time: 33:81\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2018-08-27T09:30:56Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"18qv300x\",\"uri\":\"https://www.speedrun.com/api/v1/users/18qv300x\"}],\"date\":\"2018-08-20\",\"submitted\":\"2018-08-21T01:52:14Z\",\"times\":{\"primary\":\"PT33S\",\"primary_t\":33,\"realtime\":\"PT33S\",\"realtime_t\":33,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}},{\"place\":1,\"run\":{\"id\":\"zg7gnq0z\",\"weblink\":\"https://www.speedrun.com/meow/run/zg7gnq0z\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"wdmqv6x2\",\"videos\":{\"links\":[{\"uri\":\"https://www.twitch.tv/videos/305516929\"}]},\"comment\":\"jesus this took me way too long to do\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2018-09-05T06:17:54Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"18qkywq8\",\"uri\":\"https://www.speedrun.com/api/v1/users/18qkywq8\"}],\"date\":\"2018-09-03\",\"submitted\":\"2018-09-03T20:10:04Z\",\"times\":{\"primary\":\"PT33S\",\"primary_t\":33,\"realtime\":\"PT33S\",\"realtime_t\":33,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/46wxo91r\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/wdmqv6x2\"}]}";
    static String record5 = "{\"weblink\":\"https://www.speedrun.com/meow#Any_Good_Ending\",\"game\":\"46wxo91r\",\"category\":\"w20zx3vd\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"9yo0ll1y\",\"weblink\":\"https://www.speedrun.com/meow/run/9yo0ll1y\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"w20zx3vd\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=kqWZ_1erYlo\"}]},\"comment\":\"Not too bad but room for improvement.\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2016-08-23T02:44:27Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"zxz9kn8q\",\"uri\":\"https://www.speedrun.com/api/v1/users/zxz9kn8q\"}],\"date\":\"2016-08-23\",\"submitted\":\"2016-08-23T02:44:27Z\",\"times\":{\"primary\":\"PT4M5S\",\"primary_t\":245,\"realtime\":\"PT4M5S\",\"realtime_t\":245,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}},{\"place\":2,\"run\":{\"id\":\"m7pd51em\",\"weblink\":\"https://www.speedrun.com/meow/run/m7pd51em\",\"game\":\"46wxo91r\",\"level\":null,\"category\":\"w20zx3vd\",\"videos\":{\"links\":[{\"uri\":\"https://www.twitch.tv/videos/306368512\"}]},\"comment\":\"hehe funni cat goes meow\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxz9kn8q\",\"verify-date\":\"2018-09-06T12:07:45Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"18qkywq8\",\"uri\":\"https://www.speedrun.com/api/v1/users/18qkywq8\"}],\"date\":\"2018-09-05\",\"submitted\":\"2018-09-05T22:00:57Z\",\"times\":{\"primary\":\"PT4M13S\",\"primary_t\":253,\"realtime\":\"PT4M13S\",\"realtime_t\":253,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"8gej2n93\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/46wxo91r\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/w20zx3vd\"}]}";
    static String record6 = "{\"weblink\":\"https://www.speedrun.com/Allo_Allo_Cartoon_Fun#Any\",\"game\":\"pdvp7kdw\",\"category\":\"n2yqvoek\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"pydr1dvz\",\"weblink\":\"https://www.speedrun.com/Allo_Allo_Cartoon_Fun/run/pydr1dvz\",\"game\":\"pdvp7kdw\",\"level\":null,\"category\":\"n2yqvoek\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=A--3-VO7W2M\"}]},\"comment\":null,\"status\":{\"status\":\"verified\",\"examiner\":\"y8d3z5x6\",\"verify-date\":\"2015-10-16T15:41:54Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"y8d3z5x6\",\"uri\":\"https://www.speedrun.com/api/v1/users/y8d3z5x6\"}],\"date\":\"2014-04-26\",\"submitted\":\"2015-10-16T15:41:54Z\",\"times\":{\"primary\":\"PT27M22S\",\"primary_t\":1642,\"realtime\":\"PT27M22S\",\"realtime_t\":1642,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"gde32g6k\",\"emulated\":true,\"region\":\"e6lxy1dz\"},\"splits\":null,\"values\":{}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/pdvp7kdw\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/n2yqvoek\"}]}";
    static String record7 = "{\"weblink\":\"https://www.speedrun.com/Splosion_Man#Single_Player\",\"game\":\"m1m8opd2\",\"category\":\"5dwygl0k\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"m3dr43qz\",\"weblink\":\"https://www.speedrun.com/Splosion_Man/run/m3dr43qz\",\"game\":\"m1m8opd2\",\"level\":null,\"category\":\"5dwygl0k\",\"videos\":{\"links\":[{\"uri\":\"https://www.twitch.tv/videos/171021413\"}]},\"comment\":\"Lots of work to do, still getting in the practice to remember all of the levels. I want to aim for a sub 1:30.\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxzn14xq\",\"verify-date\":\"2017-09-02T03:14:06Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"v81vmpr8\",\"uri\":\"https://www.speedrun.com/api/v1/users/v81vmpr8\"}],\"date\":\"2017-08-30\",\"submitted\":\"2017-08-31T03:08:39Z\",\"times\":{\"primary\":\"PT1H50M7S\",\"primary_t\":6607,\"realtime\":\"PT1H50M7S\",\"realtime_t\":6607,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":\"PT1H42M25S\",\"ingame_t\":6145},\"system\":{\"platform\":\"n568oevp\",\"emulated\":false,\"region\":\"e6lxy1dz\"},\"splits\":null,\"values\":{\"789k1w5l\":\"jq64vkj1\",\"2lgz5668\":\"zqoyjox1\"}}},{\"place\":2,\"run\":{\"id\":\"yl9lpnxy\",\"weblink\":\"https://www.speedrun.com/Splosion_Man/run/yl9lpnxy\",\"game\":\"m1m8opd2\",\"level\":null,\"category\":\"5dwygl0k\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=9z6UBEKgDcU\"}]},\"comment\":\"Finally did the last boss deathless, even if flies trolled me. Sub 140m is doable, just had to master some new tricks and make a lot less errors.\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxzn14xq\",\"verify-date\":\"2018-01-07T07:16:37Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"zxzn14xq\",\"uri\":\"https://www.speedrun.com/api/v1/users/zxzn14xq\"}],\"date\":\"2018-01-07\",\"submitted\":\"2018-01-07T07:16:37Z\",\"times\":{\"primary\":\"PT2H23M29S\",\"primary_t\":8609,\"realtime\":\"PT2H23M29S\",\"realtime_t\":8609,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":null,\"ingame_t\":0},\"system\":{\"platform\":\"n568oevp\",\"emulated\":false,\"region\":\"pr184lqn\"},\"splits\":{\"rel\":\"splits.io\",\"uri\":\"https://splits.io/api/v3/runs/248k\"},\"values\":{\"789k1w5l\":\"jq64vkj1\",\"2lgz5668\":\"zqoyjox1\"}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/m1m8opd2\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/5dwygl0k\"}]}";
    static String record8 = "{\"weblink\":\"https://www.speedrun.com/Splosion_Man#Multiplayers\",\"game\":\"m1m8opd2\",\"category\":\"zdn4l3qk\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/m1m8opd2\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/zdn4l3qk\"}]}";
    static String record9 = "{\"weblink\":\"https://www.speedrun.com/Splosion_Man#World_1\",\"game\":\"m1m8opd2\",\"category\":\"jdz8pjrd\",\"level\":null,\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/m1m8opd2\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/jdz8pjrd\"}]}";
    static String record10 = "{\"weblink\":\"https://www.speedrun.com/Splosion_Man/1-1#Single_Player\",\"game\":\"m1m8opd2\",\"category\":\"9kvm7mjk\",\"level\":\"ldyyrkpd\",\"platform\":null,\"region\":null,\"emulators\":null,\"video-only\":false,\"timing\":null,\"values\":{},\"runs\":[{\"place\":1,\"run\":{\"id\":\"m3dlkn4z\",\"weblink\":\"https://www.speedrun.com/Splosion_Man/run/m3dlkn4z\",\"game\":\"m1m8opd2\",\"level\":\"ldyyrkpd\",\"category\":\"9kvm7mjk\",\"videos\":{\"links\":[{\"uri\":\"https://www.youtube.com/watch?v=jSxJ4f4qWNE\"}]},\"comment\":\"One handed speed run\",\"status\":{\"status\":\"verified\",\"examiner\":\"zxzn14xq\",\"verify-date\":\"2017-12-02T20:17:32Z\"},\"players\":[{\"rel\":\"user\",\"id\":\"v81vmpr8\",\"uri\":\"https://www.speedrun.com/api/v1/users/v81vmpr8\"}],\"date\":\"2017-12-02\",\"submitted\":\"2017-12-02T19:20:37Z\",\"times\":{\"primary\":\"PT1M7S\",\"primary_t\":67,\"realtime\":null,\"realtime_t\":0,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":\"PT1M7S\",\"ingame_t\":67},\"system\":{\"platform\":\"n568oevp\",\"emulated\":false,\"region\":\"e6lxy1dz\"},\"splits\":null,\"values\":{\"789k1w5l\":\"jq64vkj1\"}}},{\"place\":2,\"run\":{\"id\":\"yw1vqdnz\",\"weblink\":\"https://www.speedrun.com/Splosion_Man/run/yw1vqdnz\",\"game\":\"m1m8opd2\",\"level\":\"ldyyrkpd\",\"category\":\"9kvm7mjk\",\"videos\":{\"links\":[{\"uri\":\"https://youtu.be/iD4jCRr2Aa8\"}]},\"comment\":null,\"status\":{\"status\":\"verified\",\"examiner\":\"zxzn14xq\",\"verify-date\":\"2017-11-26T17:45:35Z\"},\"players\":[{\"rel\":\"guest\",\"name\":\"Raigeki\",\"uri\":\"https://www.speedrun.com/api/v1/guests/Raigeki\"}],\"date\":\"2017-05-03\",\"submitted\":\"2017-11-26T17:45:35Z\",\"times\":{\"primary\":\"PT1M18S\",\"primary_t\":78,\"realtime\":null,\"realtime_t\":0,\"realtime_noloads\":null,\"realtime_noloads_t\":0,\"ingame\":\"PT1M18S\",\"ingame_t\":78},\"system\":{\"platform\":\"n568oevp\",\"emulated\":false,\"region\":null},\"splits\":null,\"values\":{\"789k1w5l\":\"jq64vkj1\"}}}],\"links\":[{\"rel\":\"game\",\"uri\":\"https://www.speedrun.com/api/v1/games/m1m8opd2\"},{\"rel\":\"category\",\"uri\":\"https://www.speedrun.com/api/v1/categories/9kvm7mjk\"},{\"rel\":\"level\",\"uri\":\"https://www.speedrun.com/api/v1/levels/ldyyrkpd\"}]}";

    @Test
    public void fromApi() {

        Gson gson = new Gson();

        ArrayList<oriolvillaret.com.api_connection_lib.models.Record> apiElems = new ArrayList<>();
        apiElems.add(gson.fromJson(record1, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record2, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record3, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record4, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record5, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record6, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record7, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record8, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record9, oriolvillaret.com.api_connection_lib.models.Record.class));
        apiElems.add(gson.fromJson(record10, oriolvillaret.com.api_connection_lib.models.Record.class));

        List<Record> appElems = RecordMapper.fromApi(apiElems);

        assertEquals(appElems.size(), apiElems.size());

        //order is important
        for (int x = 0; x < apiElems.size(); x++) {

            oriolvillaret.com.api_connection_lib.models.Record recordApi = apiElems.get(x);
            Record recordApp = appElems.get(x);
            Run run = null;
            int y = 0;
            while (run == null && y < recordApi.runs.size()) {
                run = recordApi.runs.get(y).run;
            }
            if (run != null) {
                if (run.players != null && !run.players.isEmpty()) {
                    assertEquals(recordApp.getUserFistPlace().getId(), run.players.get(0).id);
                }
                assertEquals(recordApp.getTime(), run.times.realtime_t);
                if (run.videos.links != null && !run.videos.links.isEmpty()) {
                    assertEquals(recordApp.getVideoURL(), run.videos.links.get(0).uri);
                }
            } else {
                assertEquals(recordApp, run);
            }
        }
    }
}