package oriolvillaret.com.speedrun.models.mappers;

import com.google.gson.Gson;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import oriolvillaret.com.speedrun.models.User;

import static org.junit.Assert.*;

public class UserMapperTest {

    static String user1 = "{\"id\":\"zxzn14xq\",\"names\":{\"international\":\"SuperBigKMart\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/SuperBigKMart\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#4646CE\",\"dark\":\"#6666EE\"},\"color-to\":{\"light\":\"#4646CE\",\"dark\":\"#6666EE\"}},\"role\":\"user\",\"signup\":\"2015-02-12T02:15:26Z\",\"location\":{\"country\":{\"code\":\"ca/qc\",\"names\":{\"international\":\"Quebec\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/superbigkmart\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/user/UCSxBwqGksoYOyS-9TXWTe1g\"},\"twitter\":{\"uri\":\"https://www.twitter.com/superbigkmart\"},\"speedrunslive\":{\"uri\":\"http://www.speedrunslive.com/profiles/#!/superbigkmart\"},\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/zxzn14xq\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=zxzn14xq\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=zxzn14xq\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/zxzn14xq/personal-bests\"}]}";
    static String user2 = "{\"id\":\"v81vmpr8\",\"names\":{\"international\":\"aychar\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/aychar\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"},\"color-to\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"}},\"role\":\"user\",\"signup\":\"2017-08-22T13:42:52Z\",\"location\":{\"country\":{\"code\":\"gb/eng\",\"names\":{\"international\":\"England\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/aycharizard\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/channel/UC9D0PD6Wes_HNm4acCcCIJQ\"},\"twitter\":null,\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/v81vmpr8\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=v81vmpr8\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=v81vmpr8\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/v81vmpr8/personal-bests\"}]}";
    static String user3 = "{\"id\":\"48g5ro2j\",\"names\":{\"international\":\"romscout\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/romscout\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"},\"color-to\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"}},\"role\":\"user\",\"signup\":\"2016-08-22T17:33:16Z\",\"location\":{\"country\":{\"code\":\"us\",\"names\":{\"international\":\"United States\",\"japanese\":null}},\"region\":{\"code\":\"us/ca\",\"names\":{\"international\":\"California, USA\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/romscout\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/user/romscout\"},\"twitter\":{\"uri\":\"https://www.twitter.com/romscoutSDA\"},\"speedrunslive\":{\"uri\":\"http://www.speedrunslive.com/profiles/#!/romscout\"},\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/48g5ro2j\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=48g5ro2j\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=48g5ro2j\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/48g5ro2j/personal-bests\"}]}";
    static String user4 = "{\"id\":\"qj2pl68k\",\"names\":{\"international\":\"MilsTailsPrower\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/MilsTailsPrower\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EF8239\",\"dark\":\"#EF8241\"},\"color-to\":{\"light\":\"#EF8239\",\"dark\":\"#EF8241\"}},\"role\":\"user\",\"signup\":\"2015-01-27T03:01:35Z\",\"location\":{\"country\":{\"code\":\"fr\",\"names\":{\"international\":\"France\",\"japanese\":null}}},\"twitch\":null,\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/user/MilesTailsProwerFox\"},\"twitter\":null,\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/qj2pl68k\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=qj2pl68k\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=qj2pl68k\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/qj2pl68k/personal-bests\"}]}";
    static String user5 = "{\"id\":\"18v59dvj\",\"names\":{\"international\":\"ef14\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/ef14\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"},\"color-to\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"}},\"role\":\"user\",\"signup\":\"2015-11-15T13:26:41Z\",\"location\":{\"country\":{\"code\":\"it\",\"names\":{\"international\":\"Italy\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/ef1411\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/channel/UCKWQog8unD521pgDJUEwOeg\"},\"twitter\":{\"uri\":\"https://www.twitter.com/ef141195\"},\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/18v59dvj\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=18v59dvj\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=18v59dvj\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/18v59dvj/personal-bests\"}]}";
    static String user6 = "{\"id\":\"v8lo1v8m\",\"names\":{\"international\":\"RobotCrocodilz\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/RobotCrocodilz\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"},\"color-to\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"}},\"role\":\"user\",\"signup\":\"2014-12-28T16:07:29Z\",\"location\":null,\"twitch\":null,\"hitbox\":null,\"youtube\":null,\"twitter\":null,\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/v8lo1v8m\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=v8lo1v8m\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=v8lo1v8m\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/v8lo1v8m/personal-bests\"}]}";
    static String user7 = "{\"id\":\"18vkn7nj\",\"names\":{\"international\":\"Tommyspud\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/Tommyspud\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"},\"color-to\":{\"light\":\"#EE2222\",\"dark\":\"#EE4444\"}},\"role\":\"user\",\"signup\":\"2016-06-12T01:08:43Z\",\"location\":{\"country\":{\"code\":\"us\",\"names\":{\"international\":\"United States\",\"japanese\":null}},\"region\":{\"code\":\"us/ia\",\"names\":{\"international\":\"Iowa, USA\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/tommyspud\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/user/tspudproductions\"},\"twitter\":null,\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/18vkn7nj\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=18vkn7nj\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=18vkn7nj\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/18vkn7nj/personal-bests\"}]}";
    static String user8 = "{\"id\":\"1xy595w8\",\"names\":{\"international\":\"baku_zero\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/baku_zero\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#249BCE\",\"dark\":\"#44BBEE\"},\"color-to\":{\"light\":\"#249BCE\",\"dark\":\"#44BBEE\"}},\"role\":\"user\",\"signup\":\"2015-10-19T04:52:30Z\",\"location\":{\"country\":{\"code\":\"jp\",\"names\":{\"international\":\"Japan\",\"japanese\":null}},\"region\":{\"code\":\"jp/13\",\"names\":{\"international\":\"Tokyo, Japan\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/baku_zero\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/channel/UCjVBWNLfEhw6IYAtYmnuZ3g\"},\"twitter\":{\"uri\":\"https://www.twitter.com/baku_zero\"},\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/1xy595w8\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=1xy595w8\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=1xy595w8\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/1xy595w8/personal-bests\"}]}";
    static String user9 = "{\"id\":\"pj0devrx\",\"names\":{\"international\":\"King_Theonitus\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/King_Theonitus\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#900090\",\"dark\":\"#A010A0\"},\"color-to\":{\"light\":\"#900090\",\"dark\":\"#A010A0\"}},\"role\":\"user\",\"signup\":\"2018-04-11T01:54:02Z\",\"location\":{\"country\":{\"code\":\"us\",\"names\":{\"international\":\"United States\",\"japanese\":null}},\"region\":{\"code\":\"us/or/pl\",\"names\":{\"international\":\"Portland, OR, USA\",\"japanese\":null}}},\"twitch\":null,\"hitbox\":null,\"youtube\":null,\"twitter\":null,\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/pj0devrx\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=pj0devrx\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=pj0devrx\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/pj0devrx/personal-bests\"}]}";
    static String user10 = "{\"id\":\"48g5rm2j\",\"names\":{\"international\":\"Royzoga\",\"japanese\":null},\"weblink\":\"https://www.speedrun.com/user/Royzoga\",\"name-style\":{\"style\":\"gradient\",\"color-from\":{\"light\":\"#EF8239\",\"dark\":\"#EF8241\"},\"color-to\":{\"light\":\"#EF8239\",\"dark\":\"#EF8241\"}},\"role\":\"user\",\"signup\":\"2016-08-22T02:19:08Z\",\"location\":{\"country\":{\"code\":\"us\",\"names\":{\"international\":\"United States\",\"japanese\":null}},\"region\":{\"code\":\"us/nj\",\"names\":{\"international\":\"New Jersey, USA\",\"japanese\":null}}},\"twitch\":{\"uri\":\"https://www.twitch.tv/royzoga123\"},\"hitbox\":null,\"youtube\":{\"uri\":\"https://www.youtube.com/user/royzoga\"},\"twitter\":{\"uri\":\"https://www.twitter.com/royzoga\"},\"speedrunslive\":null,\"links\":[{\"rel\":\"self\",\"uri\":\"https://www.speedrun.com/api/v1/users/48g5rm2j\"},{\"rel\":\"runs\",\"uri\":\"https://www.speedrun.com/api/v1/runs?user=48g5rm2j\"},{\"rel\":\"games\",\"uri\":\"https://www.speedrun.com/api/v1/games?moderator=48g5rm2j\"},{\"rel\":\"personal-bests\",\"uri\":\"https://www.speedrun.com/api/v1/users/48g5rm2j/personal-bests\"}]}";

    @Test
    public void fromApi() {

        Gson gson = new Gson();

        ArrayList<oriolvillaret.com.api_connection_lib.models.User> apiElems = new ArrayList<>();
        apiElems.add(gson.fromJson(user1, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user2, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user3, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user4, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user5, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user6, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user7, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user8, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user9, oriolvillaret.com.api_connection_lib.models.User.class));
        apiElems.add(gson.fromJson(user10, oriolvillaret.com.api_connection_lib.models.User.class));

        List<User> appElems = UserMapper.fromApi(apiElems);
        assertEquals(appElems.size(), apiElems.size());

        //order is important
        for (int x = 0; x < apiElems.size(); x++) {

            oriolvillaret.com.api_connection_lib.models.User userdApi = apiElems.get(x);
            oriolvillaret.com.speedrun.models.User userdApp = appElems.get(x);

            assertEquals(userdApp.getId(), userdApi.id);
            assertEquals(userdApp.getName(), userdApi.names.international);
        }
    }
}